name: Java CI with Maven

on:
  push:
    branches: [ "main" ]   # se ejecuta al hacer push en la rama main
  pull_request:
    branches: [ "main" ]   # o al crear un PR hacia main

jobs:
  build:
    runs-on: ubuntu-latest   # el entorno donde se ejecutará

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # distribución OpenJDK
          java-version: '21'

      - name: Compilar con Maven
        run: mvn -B package --file pom.xml

      - name: Ejecutar pruebas
        run: mvn test
