# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compilar y probar con Maven
      working-directory: ./backend   # ðŸ‘ˆ cambia esto segÃºn tu estructura
      run: mvn -B package --file pom.xml


    - name: Mostrar los primeros 3 caracteres del usuario (enmascarado)
      run: |
        echo "EMAIL_USER_TO empieza con: ${EMAIL_USER_TO:0:3}***"
      env:
        EMAIL_USER_TO: ${{ secrets.EMAIL_USER_TO }}    


    - name: Ejecutar pruebas
      working-directory: ./backend
      run: mvn test

    - name: obtener variable de entorno
      env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_USER_TO: ${{ secrets.EMAIL_USER_TO }}

    # ðŸ‘‡ Paso que se ejecuta solo si falla el build
    - name: Enviar correo si falla el build
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: u20191176324@usco.edu.co
        password: ${{ secrets.EMAIL_PASS }}
        subject: "ðŸš¨ Error en GitHub Actions - Calculadora"
        body: "El pipeline de CI ha fallado. Revisa los logs en GitHub Actions."
        to: stevenchicue@hotmail.com
        from: GitHub Actions <u20191176324@usco.edu.co>
